### ISSUE TITLE
No gene reports and error when using the '-a' option

### ISSUE THREAD

**Issue by minisciencegirl** [quadram-institute-bioscience/albatradis#11]
Having similar issues as well, specifically I am running albatradis -v -o OUTPUT emblfile condition_plots control_plots. This produces 7 files, without the gene_report.csv

When I run 'albatradis -v -a -o OUTPUT emblfile condition_plots control_plots', I get the following error messages:

    Error in hist.default(ii, breaks = 200, plot = FALSE) :
    'x' must be numeric
    Calls: hist -> hist.default
    Execution halted
    Traceback (most recent call last):
    File "/home/amy/anaconda3/bin/albatradis", line 63, in
    albatradis.run()
    File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/AlbaTraDIS.py", line 54, in run
    bi.run()
    File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 74, in run
    essentiality_files = self.run_essentiality(plotfile_objects)
    File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 117, in run_essentiality
    f = self.essentiality(plotfile_objects, plotfile, 'forward')
    File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 107, in essentiality
    e.run()
    File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/TradisEssentiality.py", line 22, in run
    subprocess.check_output(self.construct_command(), shell=True)
    File "/home/amy/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
    File "/home/amy/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command 'tradis_essentiality.R /tmp/tmpyljazbl2' returned non-zero exit status 1.

**Comment by sbastkowski** [comment]
Hi, so in #3 the issue was that there were no significant genes, therefore no report was created. I don't know what your input is but you could try to relax the parameters, e.g. -c 1.0, not sure about the essentiality error, could you provide your input?

**Comment by sbastkowski** [comment]
@minisciencegirl the problem is that the data is either too spares or too dense to determine a cutoff for essential genes. If they are too sparse, you shouldn't use them. If they are too dense, you could potentially subsample insertion sites.
