### ISSUE TITLE
No gene report.csv files

### ISSUE THREAD

**Issue by joeseaman** [quadram-institute-bioscience/albatradis#3]
Hi, 
is there a reason why a gene report.csv file would not be produced in the output folder. sometimes when i run albatradis it is produced and sometimes it isnt?

Thanks

**Comment by minisciencegirl** [comment]
Having similar issues as well, specifically I am running `albatradis -v -o OUTPUT emblfile condition_plots control_plots`. This produces 7 files, without the gene_report.csv

When I run 'albatradis -v -a -o OUTPUT emblfile condition_plots control_plots', I get the following error messages: 

> Error in hist.default(ii, breaks = 200, plot = FALSE) : 
  'x' must be numeric
Calls: hist -> hist.default
Execution halted
Traceback (most recent call last):
  File "/home/amy/anaconda3/bin/albatradis", line 63, in <module>
    albatradis.run()
  File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/AlbaTraDIS.py", line 54, in run
    bi.run()
  File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 74, in run
    essentiality_files = self.run_essentiality(plotfile_objects)
  File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 117, in run_essentiality
    f = self.essentiality(plotfile_objects, plotfile, 'forward')
  File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/BlockInsertions.py", line 107, in essentiality
    e.run()
  File "/home/amy/anaconda3/lib/python3.7/site-packages/albatradis/TradisEssentiality.py", line 22, in run
    subprocess.check_output(self.construct_command(), shell=True)
  File "/home/amy/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/home/amy/anaconda3/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'tradis_essentiality.R /tmp/tmpyljazbl2' returned non-zero exit status 1.

**Comment by sbastkowski** [comment]
Hi, so in https://github.com/quadram-institute-bioscience/albatradis/issues/3 the issue was that there were no significant genes, therefore no report was created. I don't know what your input is but you could try to relax the parameters, e.g. -c 1.0, not sure about the essentiality error, could you provide your input?
