### ISSUE TITLE
No module named 'graphviz'

### ISSUE THREAD

**Issue by pmireland** [quadram-institute-bioscience/albatradis#7]
Hi,

Everything else seems to be working following conda installation. However, commands using graphviz seems to fail. Any idea how to solve this issue?

Thank you

:~$ albatradis-presence_absence -h
Traceback (most recent call last):
  File "/home/phil/miniconda3/envs/py36/bin/albatradis-presence_absence", line 8, in <module>
    from albatradis.AlbaTraDISPresenceAbsence import AlbaTraDISPresenceAbsence
  File "/home/phil/miniconda3/envs/py36/lib/python3.6/site-packages/albatradis/AlbaTraDISPresenceAbsence.py", line 6, in <module>
    from albatradis.PresenceAbsence import PresenceAbsence
  File "/home/phil/miniconda3/envs/py36/lib/python3.6/site-packages/albatradis/PresenceAbsence.py", line 13, in <module>
    from graphviz import Digraph
ModuleNotFoundError: No module named 'graphviz'

:~$ albatradis-artemis_project -h
Traceback (most recent call last):
  File "/home/phil/miniconda3/envs/py36/bin/albatradis-artemis_project", line 8, in <module>
    from albatradis.AlbaTraDISArtemisProject import AlbaTraDISArtemisProject
  File "/home/phil/miniconda3/envs/py36/lib/python3.6/site-packages/albatradis/AlbaTraDISArtemisProject.py", line 3, in <module>
    from albatradis.ArtemisProject import ArtemisProject
  File "/home/phil/miniconda3/envs/py36/lib/python3.6/site-packages/albatradis/ArtemisProject.py", line 7, in <module>
    from albatradis.PresenceAbsence import PresenceAbsence
  File "/home/phil/miniconda3/envs/py36/lib/python3.6/site-packages/albatradis/PresenceAbsence.py", line 13, in <module>
    from graphviz import Digraph
ModuleNotFoundError: No module named 'graphviz'

**Comment by thanhleviet** [comment]
Hi @pmireland,

Thanks for reporting the bug. 
You can install the missing python package by this command: 

`conda install -c anaconda python-graphviz`

We will update the fix on bioconda soon.
Thanh

**Comment by thanhleviet** [comment]
Fixed missing python packaged and bumped to version 1.0.0 on bioconda

**Comment by EuridiceOrpheu** [comment]
![image](https://user-images.githubusercontent.com/35822003/64860399-b3395300-d635-11e9-8ebd-e8bc2dd3cc1d.png)
How do I solve this ?

**Comment by andrewjpage** [comment]
@EuridiceOrpheu  What version of AlbaTraDIS produced this error? I cant see any references to our code in the error messages.

**Comment by EuridiceOrpheu** [comment]
Sorry ,The issue does not fit for this module .
